title: Research Bit
email: your-email@example.com
description: Mfc Website
baseurl: "/bit"
url: "https://research.mf-chan.com"
twitter_username:
github_username:  moefc32

theme: minima
plugins:
  - jekyll-feed
